services:
  luren-bot:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./backend
          target: /app/discord-bot-go
    container_name: luren-bot
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
    restart: unless-stopped
