# Stage 1: Build Backend
FROM golang:1.23 AS backend
ENV GOFLAGS="-mod=vendor"
WORKDIR /build/backend
COPY backend/. ./
RUN GOOS=linux GOARCH=amd64 go build -mod vendor -o bin/discord-bot-go main/main.go

# Stage 2: Export content
FROM scratch AS export
COPY --from=backend /build/backend/bin/discord-bot-go ./
